server:
    port: 8888

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      #routes:
      #- id: stock
      #  uri: lb://stock
      #  predicates: 
      #  - Path=/stock/**
      #  filters:
      #  - RewritePath=/stock/(?<path>.*), /$\{path}

eureka:
  client:
    service-url: 
      default-zone: "http://localhost:8761/eureka/"
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 1
  server:
      enableSelfPreservation: false


management:
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: "*"