server:
    port: 8889

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: stock
        uri: lb://stock
        predicates: 
        - Path=/stock/**
        filters:
        - RewritePath=/stock/(?<path>.*), /$\{path}
          
#spring.cloud.gateway.routes[0].id=users
#spring.cloud.gateway.routes[0].uri=lb://PHOTOAPPAPI-USERS/users
#spring.cloud.gateway.routes[0].predicates[0]=Path=/users/**

eureka:
  client:
    service-url: 
      default-zone: "http://localhost:8761/eureka/"
  server:
      enableSelfPreservation: false


management:
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: "*"